// components/layout/Footer.tsx
import React from "react";

export interface FooterProps {
  lang: "en" | "ar";
  rtl?: boolean;
  settings?: {
    facebook?: string;
    linkIn?: string;
    twitter?: string;
    instagram?: string;
  };
}

export const Footer: React.FC<FooterProps> = ({ lang, rtl, settings }) => {
  return (
    <footer className={`footer${rtl ? " rtl" : ""}`}> {/* Main footer */}
      <div className="container foot-div">
        <div>
          <div><a href={`/${lang}/solutions`}>المنزل الذكي</a></div>
          <div><a href={`/${lang}/products`}>المنتجات</a></div>
          <div><a href={`/${lang}/about`}>من نحن</a></div>
          <div><a href={`/${lang}/contact`}>اتصل بنا</a></div>
        </div>
        <div className="img-svg">
          {settings?.facebook && (
            <a href={settings.facebook} target="_blank" rel="noopener noreferrer">
              <img alt="facebook page" src="/images/logos/facebook.svg" />
            </a>
          )}
          {settings?.linkIn && (
            <a href={settings.linkIn} target="_blank" rel="noopener noreferrer">
              <img alt="linkedin page" src="/images/logos/linkedin.svg" />
            </a>
          )}
          {settings?.twitter && (
            <a href={settings.twitter} target="_blank" rel="noopener noreferrer">
              <img alt="twitter page" src="/images/logos/twitter.svg" />
            </a>
          )}
          {settings?.instagram && (
            <a href={settings.instagram} target="_blank" rel="noopener noreferrer">
              <img alt="instagram page" src="/images/logos/instagram.svg" />
            </a>
          )}
        </div>
        <div className="logo-container">
          <img src="/images/logos/logoWhite.png" alt="Alhayat Smart Logo" className="imag-svg" />
        </div>
      </div>
      <div className="copyRights">
        <p className="copy-rights-text">جميع الحقوق محفوظة &copy; الحياة سمارت</p>
        <p className="powered-by-text">برمجة وتطوير: <a href="https://alhayatsmart.com" target="_blank" rel="noopener noreferrer">Alhayat Smart</a></p>
      </div>
      <div style={{ position: "absolute", bottom: 10 }}>
        <div className="floating-button-div">
          <a href="tel:00201206569999">
            <i className="fas fa-phone-alt circle-phone"></i>
          </a>
        </div>
        <p className="hotline">Hotline: 01206569999</p>
      </div>
    </footer>
  );
};

export default Footer;

// src/app/footer/footer.component.ts
import {Component, OnInit, ViewEncapsulation} from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { TranslateService } from '@ngx-translate/core';
import {Globals} from '../servicesApi/globals';
import {NgxSpinnerService} from 'ngx-spinner';
import {ApiCalledService} from '../servicesApi/api-called.service';
import {Settings} from '../interfaces.module';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.css'],
  encapsulation: ViewEncapsulation.None,
})

export class FooterComponent implements OnInit {
  lang = 'en';
  rtl: string;
  settings = new Settings();
  constructor(public translate: TranslateService, private route: ActivatedRoute,  private globals: Globals,
              private apiCalledService: ApiCalledService, private spinner: NgxSpinnerService) {
  }

  ngOnInit() {
    this.globals.getLang().subscribe(lang => {
     this.lang = lang;
     if ( this.lang === 'ar' ) {
        this.rtl = 'rtl';
      } else {
        this.rtl = '';
      }
    });

    this.apiCalledService.getSettings().subscribe(data => {
      this.spinner.hide();
      this.settings = data;
    });
  }
}

<footer class="footer  {{rtl}}">
    <div class="container foot-div ">
      <div>
        <div><a routerLink="/{{lang}}/Solutions">{{'Locale.smartHome' | translate}}</a></div>
        <div><a routerLink="/{{lang}}//Products">{{'Locale.products' | translate}}</a></div>
        <div><a routerLink="/{{lang}}//about">{{'Locale.aboutUs' | translate}}</a></div>
        <div><a routerLink="/{{lang}}//contact">{{'Locale.contactUs' | translate}}</a></div>
      </div>
        <div  class="img-svg">
          <a href="{{settings.facebook}}" target="_blank"><img alt="facebook page" src="assets\smart-image\facebook.svg"></a>
          <a href="{{settings.linkIn}}" target="_blank"><img alt="linkedin page" src="assets\smart-image\linkedin.svg"></a>
          <a href="{{settings.twitter}}" target="_blank"><img alt="twitter page"  src="assets\smart-image\twitter.svg"></a>
          <a href="{{settings.instagram}}" target="_blank"><img alt="instagram page" src="assets\smart-image\instagram.svg"></a>
        </div>
        <div class="logo-container"><img src="assets/smart-image/logoWhite.png" alt="Alhayat Smart Logo" class="imag-svg"></div>
    </div>
    <div class="copyRights">
      <p class="copy-rights-text">{{"Locale.copyRights" | translate}}</p>
      <p class="powered-by-text" [innerHTML]="'Locale.poweredBy' | translate"></p>
    </div>
<div style="position: absolute; bottom: 10px;">

  <div class="floating-button-div">
    <a href="tel:00201206569999">  <i class="fas fa-phone-alt circle-phone"></i> </a>
  </div>
  <p class="hotline"> {{'Locale.hotLine' | translate }} </p>
</div>
</footer>
