// src/app/nav-bar/nav-bar.component.ts
import {AfterViewInit, Component, OnInit} from '@angular/core';
import {ActivatedRoute, Router, RoutesRecognized, NavigationEnd} from '@angular/router';
import {ApiCalledService} from '../servicesApi/api-called.service';
import {Globals} from '../servicesApi/globals';
import {NgxSpinnerService} from 'ngx-spinner';
import {TranslateService} from '@ngx-translate/core';
import {Basket, Settings, User} from '../interfaces.module';
import {NgbDropdownConfig} from '@ng-bootstrap/ng-bootstrap';
import { HostListener } from '@angular/core';
declare let gtag: Function;
@Component({
  selector: 'app-nav-bar',
  templateUrl: './nav-bar.component.html',
  styleUrls: ['./nav-bar.component.css'],
  providers: [NgbDropdownConfig]
})
export class NavBarComponent implements OnInit, AfterViewInit {
  user: User;
  categories;
  lang;
  switchLangUrl: string;
  rtl: string;
  basket: Basket[];
  basketCount = 0;
  settings = new Settings();
  public isCollapsed = true;
  navScroll = false;
  constructor(private route: ActivatedRoute, private apiCalledService: ApiCalledService, private globals: Globals,
              private router: Router, private translate: TranslateService, private spinner: NgxSpinnerService, config: NgbDropdownConfig,
              ) {
    config.autoClose = 'outside';
    translate.addLangs(['en', 'ar']);
    translate.setDefaultLang('en');
  }
  logOut() {
    this.globals.setUser(null);
    this.router.navigate([this.lang]);
    return localStorage.removeItem('user');
  }
  @HostListener('document:scroll')
  scrollFunction() {
    this.navScroll = document.documentElement.scrollTop > 30;
  }

  ngOnInit() {
    this.router.events.subscribe(val => {
      if (val instanceof RoutesRecognized) {
        // this.switchLangUrl = this.route.snapshot;
        if (val.state.root.firstChild.params.language) {
          this.globals.setLang(val.state.root.firstChild.params.language);
        } else {
          this.globals.setLang('en');
        }
        if (val.state.root.firstChild.params.language === 'ar') {
          this.switchLangUrl = '/en';
        } else {
          this.switchLangUrl = '/ar';
        }
        val.state.root.children[0].url.forEach(value => {
            if (value.path !== 'en' && value.path !== 'ar') {
              this.switchLangUrl += '/' + value.path;
            }
          }
        );
      }
      if (val instanceof NavigationEnd) {
        this.apiCalledService.getSettings().subscribe(data => {
          this.spinner.hide();
          this.settings = data;
        });
        gtag('config', 'UA-144674258-5', {page_path: val.urlAfterRedirects});
      }
    });
    if (localStorage.getItem('user')) {
      this.globals.setUser(JSON.parse(localStorage.getItem('user')));
    }
    this.globals.getLang().subscribe(lang => {
        if (lang !== undefined && lang !== this.lang) {
          this.lang = lang;
          this.translate.use(this.lang);
          if (this.lang === 'ar') {
            this.rtl = 'rtl';
          } else {
            this.rtl = '';
          }
          this.apiCalledService.getCategories(this.lang).subscribe(data => {
            this.categories = data.parent;
            this.globals.setCategories(this.categories);
            this.spinner.hide();
          });
          if (this.user) {

            this.getBasket();
          } else if (localStorage.getItem('basket')) {
            this.globals.setBasket(JSON.parse(localStorage.getItem('basket')));
          }
        }
      }
    );

    this.globals.getUser().subscribe(user => {
      this.user = user;
      if (this.user) {
        if (!this.user.image) {
          this.user.image = 'assets/smart-image/icons8-user-80.png';
        }
        if (this.lang) {

          if (localStorage.getItem('basket')) {

            const basket = JSON.parse(localStorage.getItem('basket'));
            basket.products.forEach((value, index) => {
              this.apiCalledService.addToBasket(value, this.user.api_token).subscribe(res => {
               if (index === basket.products.length - 1) {
                 this.getBasket();
                 localStorage.removeItem('basket');
               }
              });
            });
          } else {
            this.getBasket();
          }

        }
      }
    });
  }

  ngAfterViewInit() {
    this.globals.getBasket().subscribe(val => {
      if (val) {
        this.basketCount = val.products.length;
      }

    });
  }

  getBasket() {
    this.apiCalledService.getBasket(this.lang, this.user.api_token).subscribe(res => {
      if (res.message !== 'basket Empty') {
        this.globals.setBasket(res);
      }
      this.spinner.hide();
    },
    error => {
      this.spinner.hide();
    }
      );
  }
}

<div class="container-lg">
  <div class="row contact-nav">
    <div  class="col-lg-4    col-md-3   col-sm-6 col-xs contact-nav-item">
      <a href="tel:00201206569999" class="contact-nav-item-link"> <i class="fas fa-phone-alt"></i> 01206569999 </a>
    </div>
    <div  class="col-lg-4    col-md-4   col-sm-6 col-xs contact-nav-item mail-div">
      <a href = "mailto: info@elhayatsmart.com" class="contact-nav-item-link"> <i class="fas fa-envelope"></i> contactus@alhayatsmart.com </a>
    </div>
    <div  class="col-lg-4    col-md-4   contact-nav-item img-div">
      <a    href="{{settings.facebook}}"   target="_blank"> <img alt="facebook page"  src="assets\smart-image\facebook.svg"></a>
      <a    href="{{settings.linkIn}}"    target="_blank"> <img alt="linkedin page"  src="assets\smart-image\linkedin.svg"></a>
      <a    href="{{settings.twitter}}"    target="_blank"> <img alt="twitter page"   src="assets\smart-image\twitter.svg"></a>
      <a    href="{{settings.instagram}}"  target="_blank"> <img alt="instagram page" src="assets\smart-image\instagram.svg"></a>    </div>
  </div>
</div>
<!--------------------------------------------------------------------->
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light{{rtl}}" [class.navbar-scrolled]="navScroll" >
  <div class="col-3">
    <a id="homeLink" routerLink="/{{lang}}">
      <img class="logo" src="assets/smart-image/Logo.png" [class.logo-scrolled]="navScroll">
    </a>
  </div>
  <div class="collapse navbar-collapse col-lg-9" #navbar="ngbCollapse" [ngbCollapse]="isCollapsed"
       id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto main-navigation  col-lg-7">
      <li class="nav-item col-lg-4">
        <a class="nav-link" (click)="$event.stopPropagation(); navbar.collapsed=true;isCollapsed=true"
           routerLink="/{{lang}}">{{'Locale.home' | translate}}</a>
      </li>
      <li class="nav-item col-lg-4">
        <a class="nav-link" style="min-width: 116px"
           (click)="$event.stopPropagation(); navbar.collapsed=true;isCollapsed=true"
           routerLink="/{{lang}}/smart-home">{{'Locale.smartHome' | translate}}</a>
      </li>
      <li class="nav-item col-lg-4">
        <!-- <a style="margin-right:40px" class="nav-link" routerLink="/solution"></a> -->
        <div class="btn-group " >
          <a routerLink="/{{lang}}/products/"  class="nav-link">
            {{'Locale.products' | translate}}
          </a>

        </div>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto  col-lg-5 last-nav">
      <li *ngIf="user" ngbDropdown class="personal-data nav-item dropdown-toggle" id="dropdownProfile"
          ngbDropdownToggle>
        <div class="dropdown">
          <div aria-labelledby="dropdownProfile" ngbDropdownMenu >
            <a ngbDropdownItem routerLink="/{{lang}}/profile">{{"Locale.account" | translate}}</a>
            <a ngbDropdownItem routerLink="/{{lang}}/orders">{{"Locale.myOrders" | translate}}</a>
            <a (click)="logOut()" ngbDropdownItem>{{"Locale.logOut" | translate}}</a>
          </div>
        </div>
        <p>{{user.name}}</p>
        <div class="user-image" [style.background-image]="'url('+user.image+')'">
        </div>
      </li>
      <li *ngIf="!user" class="nav-item">
        <a  (click)="$event.stopPropagation(); navbar.collapsed=true;isCollapsed=true" class="nav-link" routerLink="/{{lang}}/signup">{{'Locale.signUp' | translate}}</a>
      </li>

      <li *ngIf="!user" class="nav-item ">
        <a class="nav-link " (click)="$event.stopPropagation(); navbar.collapsed=true;isCollapsed=true" routerLink="/{{lang}}/login">{{'Locale.login' | translate}}</a>
      </li>
      <li class="nav-item basket-icon ">
        <a (click)="$event.stopPropagation(); navbar.collapsed=true;isCollapsed=true" routerLink="/{{lang}}/cart">
          <img class="icon-shop" src="assets/smart-image/icon-shop.svg">
          <span class="count-num">{{basketCount}}</span>
        </a>
      </li>
      <li class="nav-item">
        <a (click)="$event.stopPropagation(); navbar.collapsed=true;isCollapsed=true" [routerLink]="switchLangUrl" *ngIf="lang=='ar'">
          {{'Locale.en' | translate}}
        </a>
        <a  (click)="$event.stopPropagation(); navbar.collapsed=true;isCollapsed=true" [routerLink]="switchLangUrl" *ngIf="lang=='en'">
          {{'Locale.en' | translate}}
        </a>
      </li>
    </ul>
  </div>
  <button aria-controls="navbarSupportedContent" class="navbar-toggler"
          [attr.aria-expanded]="!isCollapsed"
          (click)="isCollapsed = !isCollapsed" type="button">
    <span class="navbar-toggler-icon"></span>
  </button>
</nav>

// components/layout/NavBar.tsx
import React from "react";

export interface NavBarProps {
  user?: { name: string; image?: string };
  basketCount: number;
  lang: "en" | "ar";
  rtl?: boolean;
  settings?: {
    facebook?: string;
    linkIn?: string;
    twitter?: string;
    instagram?: string;
  };
  onLogout?: () => void;
  onLangSwitch?: (lang: "en" | "ar") => void;
}

export const NavBar: React.FC<NavBarProps> = ({
  user,
  basketCount,
  lang,
  rtl,
  settings,
  onLogout,
  onLangSwitch,
}) => {
  return (
    <nav className={`navbar fixed-top navbar-expand-lg navbar-light bg-light${rtl ? " rtl" : ""}`}> {/* Top nav */}
      <div className="container-lg">
        {/* Contact bar */}
        <div className="row contact-nav">
          <div className="col-lg-4 col-md-3 col-sm-6 col-xs contact-nav-item">
            <a href="tel:00201206569999" className="contact-nav-item-link">
              <i className="fas fa-phone-alt"></i> 01206569999
            </a>
          </div>
          <div className="col-lg-4 col-md-4 col-sm-6 col-xs contact-nav-item mail-div">
            <a href="mailto:info@alhayatsmart.com" className="contact-nav-item-link">
              <i className="fas fa-envelope"></i> contactus@alhayatsmart.com
            </a>
          </div>
          <div className="col-lg-4 col-md-4 contact-nav-item img-div">
            {settings?.facebook && (
              <a href={settings.facebook} target="_blank" rel="noopener noreferrer">
                <img alt="facebook page" src="/images/logos/facebook.svg" />
              </a>
            )}
            {settings?.linkIn && (
              <a href={settings.linkIn} target="_blank" rel="noopener noreferrer">
                <img alt="linkedin page" src="/images/logos/linkedin.svg" />
              </a>
            )}
            {settings?.twitter && (
              <a href={settings.twitter} target="_blank" rel="noopener noreferrer">
                <img alt="twitter page" src="/images/logos/twitter.svg" />
              </a>
            )}
            {settings?.instagram && (
              <a href={settings.instagram} target="_blank" rel="noopener noreferrer">
                <img alt="instagram page" src="/images/logos/instagram.svg" />
              </a>
            )}
          </div>
        </div>
        {/* Main nav */}
        <div className="navbar-content">
          <a id="homeLink" href={`/${lang}`}>
            <img className="logo" src="/images/logos/Logo.png" alt="Alhayat Smart Logo" />
          </a>
          <ul className="navbar-nav main-navigation">
            <li className="nav-item">
              <a className="nav-link" href={`/${lang}`}>الرئيسية</a>
            </li>
            <li className="nav-item">
              <a className="nav-link" href={`/${lang}/smart-home`}>المنزل الذكي</a>
            </li>
            <li className="nav-item">
              <a className="nav-link" href={`/${lang}/products`}>المنتجات</a>
            </li>
          </ul>
          <ul className="navbar-nav last-nav">
            {user ? (
              <li className="nav-item personal-data">
                <div className="user-image" style={{ backgroundImage: `url(${user.image || "/images/logos/user.png"})` }} />
                <span>{user.name}</span>
                <div className="dropdown">
                  <a href={`/${lang}/profile`}>الحساب</a>
                  <a href={`/${lang}/orders`}>طلباتي</a>
                  <a href="#" onClick={onLogout}>تسجيل الخروج</a>
                </div>
              </li>
            ) : (
              <>
                <li className="nav-item">
                  <a className="nav-link" href={`/${lang}/signup`}>تسجيل جديد</a>
                </li>
                <li className="nav-item">
                  <a className="nav-link" href={`/${lang}/login`}>دخول</a>
                </li>
              </>
            )}
            <li className="nav-item basket-icon">
              <a className="nav-link" href={`/${lang}/cart`}>
                <img className="icon-shop" src="/images/logos/icon-shop.svg" alt="سلة المشتريات" />
                <span className="count-num">{basketCount}</span>
              </a>
            </li>
            <li className="nav-item">
              <button onClick={() => onLangSwitch?.(lang === "ar" ? "en" : "ar")}>{lang === "ar" ? "EN" : "AR"}</button>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  );
};

export default NavBar;
